### ISSUE TITLE
Enable boot mode on an STM32 aliexpress clone

### ISSUE THREAD

**Issue by sysadminpower2019** [phl0/MMDVM_HS_Dual_Hat#13]
Hello,

I have been trying to update my firmware for this board but have no had any luck. Apparently it needs to be put into bootloader mode but there does not seem to be any obvious place on the board to work with.

Here is a link to the board. Hopefully at least someone can point me in the right direction to try things out. 

https://www.aliexpress.com/item/1005006281394445.html
![Duplex-MMDVM-Hotspot-MMDVM-HS-Dual-Hat-Duplex-MMDVM-Hot_002-ezgif com-rotate](https://github.com/phl0/MMDVM_HS_Dual_Hat/assets/40726534/0313c258-3852-4157-88f3-dc4839eb4b87)

the chip seems to be a geehy apm32 f103cbt6

thanks very much

**Comment by phl0** [comment]
This board is not supported by this repo. Please contact the seller. Sorry.

**Comment by sysadminpower2019** [comment]
I contacted the seller they said their distributor has no idea either. Any idea where I could turn to support for this board?

**Comment by phl0** [comment]
> I contacted the seller they said their distributor has no idea either. Any idea where I could turn to support for this board?

Nope sri.
