### ISSUE TITLE
Not able to open 2.0-mini schematic because there is a .sch file missing.

### ISSUE THREAD

**Issue by pufferfish42** [phl0/MMDVM_HS_Dual_Hat#7]
Hello,
I am trying to build the 2.0-mini schematic. However the *.sch files are missing, so it is not possible to open the project. Could you please submit the *.sch files?
Thanks in advance!

**Comment by phl0** [comment]
There is a .kicad_sch file. You may need a more recent version of KiCad ;-)

**Comment by pufferfish42** [comment]
I am using latest stable version of Kicad (5.1.8) in Fedora. Are you using nightly builds of Kicad?
