### ISSUE TITLE
Kicad files for DUAL HAT

### ISSUE THREAD

**Issue by PD5DJ** [phl0/MMDVM_HS_Dual_Hat#9]
Where can we find the Kicad files for the Dual hat?
Specially Step files for the PCB

I like to make a custom Enclosure for the Dual HAT.

**Comment by phl0** [comment]
See the [hardware folder](https://github.com/phl0/MMDVM_HS_Dual_Hat/tree/master/hardware) in this repo.

**Comment by PD5DJ** [comment]
Ahhh missed the v1.3 folder tnx!
